### ISSUE TITLE
How to enable draw initially

### ISSUE THREAD

**Issue by muralibobby35** [RavishaHesh/PDFJsAnnotations#17]
After loading the page by default how to enable draw mode instead of enableselector? i tried to trigger pencil() but not working.

**Comment by RavishaHesh** [comment]
Actually to that in the correct way I have to add a callback function option to the library so once all the pages get rendered it can call to the callback function Since this is not implemented for now what you can do is, after initialization add a setTimeout for 1 second and call  enablePencil method inside that
```javascript
var pdf = new PDFAnnotate('pdf-container', 'pdf.pdf');

setTimeout(() => {
    pdf.enablePencil();
}, 1000);
```

**Comment by muralibobby35** [comment]
Thanks,
How to disable pdf for user? even not select tool also?

**Comment by muralibobby35** [comment]
Please let me know how to disable all actions on pdf? Actually i have to enable pdf actions through signal. So before viewer has only view mode.
