### ISSUE TITLE
Question: Can npm package to make it available to use in existing projects?

### ISSUE THREAD

**Issue by abhimanusharma** [RavishaHesh/PDFJsAnnotations#19]
Hi,

Can we remove jQuery completely from this project and make it as a plugin/ npm package to use it inside other project?

Such as, `npm install pdfjs-annotation` 

I am already trying to do something like this, by using this package in my vuejs project. 

Let me known if it is possible.

**Comment by RavishaHesh** [comment]
Honestly I don't have a plan to add this version to the NPM registry because code base is bit messy since I have written this in my early days as a software developer. There's a work in progress code base in dev branch which I'm planning to deploy to the NPM registry. I'm trying to add text rendering feature to that as well since that is the major drawback of this version. Unfortunately I haven't had time to continue the work on that branch in months. 

you should be able to use this with VueJS. Try to initialize the plugin inside `mount` method and then assign plugin instance to a data variable(I have recently tried this method with bootstrap-datatable and VueJS).

**Comment by abhimanusharma** [comment]
I have implemented this plugin with vuejs successfully, only thing I am struggling with is storing the annotation state (JSON) in database and then load it later.

I am working on a private project so unable to share video of what I am trying to achieve to give you the clear picture, if you could provide me your email, I will share more information with you there.

**Comment by RavishaHesh** [comment]
Can you create a  jsFiddle with the function that you are trying to implement. No need for the exact logic. piece of code to give the basic idea of your implementation

**Comment by RavishaHesh** [comment]
Hope you have manged to find a solution your issue. Feel free to open again if you have further questions
