### ISSUE TITLE
Save pdf to server side with ajax or else

### ISSUE THREAD

**Issue by helmyfikrih** [RavishaHesh/PDFJsAnnotations#27]
is it possible to save drawed file to server side? maybe it's using ajax or else to store edited pdf to server?

**Comment by RavishaHesh** [comment]
I guess you want to send PDF file via ajax right? Right now library only supports to save PDF as a JSON or download PDF. but with little-bit of tinkering you should be able get jsPDF instance. the line you need to modify is 232 `doc.save(fileName);` and this with this [method](http://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html#output) you should be able to get a blob

**Comment by helmyfikrih** [comment]
I'm done with this
change 

`doc.save(fileName);`

with 

`var pdf = btoa(doc.output());
      $.ajax({
        method: "POST",
        url: "test.php",
        data: { data: pdf },
      }).done(function (data) {});
`

thanks sir. your library help me. And I thing need improvement bcs I found some bugs with event listener.

**Comment by RavishaHesh** [comment]
You are welcome. I'm glad I was able to help.
Yeah I know there are some bug since this a 3years old code-base. I'm working on a new version with text layer support since that's the biggest issue with. But with my higher studies I don't have enough time to work on these until around April.
I'm gonna close this one. Feel free to open again if you have further queries.

**Comment by jesesqui** [comment]
> I'm done with this change
> 
> `doc.save(fileName);`
> 
> with
> 
> `var pdf = btoa(doc.output()); $.ajax({ method: "POST", url: "test.php", data: { data: pdf }, }).done(function (data) {}); `
> 
> thanks sir. your library help me. And I thing need improvement bcs I found some bugs with event listener.
where put the var pdf=...., can I see your example? THX
